# -*- coding: utf-8 -*-
"""Data preprocessing - obesity challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DORZMYXj9xJwskeRdzkLFyvljBk3Df1V

Steps:
-  Convert the train and test data to CUIs
1. Convert xml file to txt
2. Use Ctake to get CUIs (xmi file)
3. read xmi file, extract CUIs, and convert to txt
"""

from google.colab import drive
drive.mount('/content/drive')

import xml.etree.ElementTree as ET
import os
#https://docs.python.org/3/library/xml.etree.elementtree.html
import pandas as pd
import re

# convert xml to individual txt for ctakes pipeline to process and extract CUI
def xml2txts(file_path, out_path): 
  text = ET.parse(file_path)
  for patient in text.iter('doc'):
  #print(patient.attrib)
    uid = patient.attrib['id']
    notes = patient[0].text
    path = f"{out_path}{uid}.txt"
    with open(path, 'w') as f:
      f.write(notes)

"""# Step 1: Convert raw data to individual txt per patient"""

file_path_test = '/content/drive/My Drive/Obesity challenge/obesity_patient_records_test.xml'
out_path_test = "/content/drive/My Drive/Obesity challenge/test_data_txt/"

# process test data into files
xml2txts(file_path_test, out_path_test)

# process train data into txt files
file_path_train1 = '/content/drive/My Drive/Obesity challenge/obesity_patient_records_training.xml'
out_path_train1 = "/content/drive/My Drive/Obesity challenge/train_data_txt/"
file_path_train2 = '/content/drive/My Drive/Obesity challenge/obesity_patient_records_training2.xml'
out_path_train2 = "/content/drive/My Drive/Obesity challenge/train_data2_txt/"

xml2txts(file_path_train1, out_path_train1)
xml2txts(file_path_train2, out_path_train2)



"""# Step 2: Process txt files with clinical notes with Apache ctakes (offline)

# Step 3: Extract CUIs from processed xmi files
"""

def extractCUIs4Patient(patient_xmi_path='/content/drive/My Drive/Obesity challenge/test_data_output/3.txt.xmi'):
  singleDoc = ET.parse(patient_xmi_path)
  patient_id = int(re.findall('\d+(?=.txt.xmi)',patient_xmi_path)[0])
  res = []
  for unit in singleDoc.iter("{http:///org/apache/ctakes/typesystem/type/refsem.ecore}UmlsConcept"):
    current_cui = unit.attrib['cui']
    res.append(current_cui)
  result = " ".join(res)
  return patient_id, result

mimic_path = "/content/drive/My Drive/MIMIC/output_first_half_selected/"
for file in os.listdir(mimic_path):
  file_path = mimic_path+file
  try:
    id, res = extractCUIs4Patient(file_path)
    with open(f'/content/drive/My Drive/MIMIC/output_first_half_selected_cuis/patient_{id}.txt', 'w') as f:
      f.write(res)
  except:
    print ("An exeption occured")
    continue
  i+=1
  if i%100==0:
    print(f"finished extracting {i} files...")

#for obesity data
i=0
train_data_path = "/content/drive/My Drive/Obesity challenge/train_data_output1/"
for file in os.listdir(train_data_path):
  file_path = train_data_path+file
  id, res = extractCUIs4Patient(file_path)
  with open(f'/content/drive/My Drive/Obesity challenge/train_data_cuis/{id}.txt', 'w') as f:
    f.write(res)
  i+=1
  if i%10==0:
    print(f"finished extracting {i} files...")